/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.itson.presentacion;

import com.itson.dominio.NotaRemision;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import negocio.ILogica;
import negocio.LogicaNegocio;

/**
 *
 * @author alexasoto
 */
public class FrmConsulNota extends javax.swing.JFrame {

    ILogica logica = new LogicaNegocio();
    private NotaRemision nota;
    Long user;
    /**
     * Creates new form FrmConsulNota
     */
    public FrmConsulNota(NotaRemision nota, Long user) {
        this.nota = nota;
        this.user=user;
        initComponents();
        this.setLocationRelativeTo(null);
        setResizable(false);
        
        if(nota!=null){
            this.txtCliente.setText(nota.getCliente().getNombre());
            this.txtDireccion.setText(nota.getCliente().getDireccion());
            this.txtTelefono.setText(nota.getCliente().getTelefono());
            this.txtFechaRecep.setText(nota.getFecha_recepcion().toString());
            this.txtFechaEnt.setText(nota.getFecha_entrega().toString());
            this.txtTotal.setText(String.valueOf(nota.getTotal()));
            this.txtAnticipo.setText(String.valueOf(nota.getAnticipo()));
            for(int i=0;i<nota.getNotaServicios().size();i++){
                this.tblServicios.setValueAt(nota.getNotaServicios().get(i).getServicio().getDescripcion(), i, 0);
                this.tblServicios.setValueAt(nota.getNotaServicios().get(i).getCant(), i, 1);
                this.tblServicios.setValueAt(nota.getNotaServicios().get(i).getServicio().getPrecio(), i, 2);
                this.tblServicios.setValueAt(nota.getNotaServicios().get(i).getPrecio(), i, 3);
                this.tblServicios.setValueAt(nota.getNotaServicios().get(i).getDetalles(), i, 4);
                this.tblServicios.setValueAt(nota.getNotaServicios().get(i).getPerdidas(), i, 5);
            }
        }
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
        //Listener para el evento de cierre
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
 
                FrmPrincipal notas = new FrmPrincipal();
                notas.setVisible(true);
            }
        });
        
        pack();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        lblNota = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        lblTelefono = new javax.swing.JLabel();
        lblCliente1 = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        txtAnticipo = new javax.swing.JTextField();
        txtFechaEnt = new javax.swing.JTextField();
        lblServicios1 = new javax.swing.JLabel();
        lblAnticipo = new javax.swing.JLabel();
        lblEntrega1 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        txtCliente = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        lblRecep = new javax.swing.JLabel();
        txtFechaRecep = new javax.swing.JTextField();
        scrlServicios = new javax.swing.JScrollPane();
        tblServicios = new javax.swing.JTable();
        btnCancelarNota = new javax.swing.JButton();
        btnEntregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consultar nota de remisión");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlFondo.setBackground(new java.awt.Color(255, 255, 255));
        pnlFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNota.setFont(new java.awt.Font("Kannada MN", 0, 20)); // NOI18N
        lblNota.setText("Consultar nota de remisión");
        pnlFondo.add(lblNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnRegresar.setBackground(new java.awt.Color(153, 204, 255));
        btnRegresar.setFont(new java.awt.Font("Kannada MN", 1, 14)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.setFocusable(false);
        btnRegresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegresar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        pnlFondo.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 100, -1));

        lblTelefono.setFont(new java.awt.Font("Kannada MN", 1, 14)); // NOI18N
        lblTelefono.setText("Teléfono:");
        pnlFondo.add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        lblCliente1.setFont(new java.awt.Font("Kannada MN", 1, 14)); // NOI18N
        lblCliente1.setText("Cliente:");
        pnlFondo.add(lblCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        lblDireccion.setFont(new java.awt.Font("Kannada MN", 1, 14)); // NOI18N
        lblDireccion.setText("Dirección:");
        pnlFondo.add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        txtAnticipo.setEditable(false);
        txtAnticipo.setFont(new java.awt.Font("Kannada Sangam MN", 0, 14)); // NOI18N
        pnlFondo.add(txtAnticipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 100, -1));

        txtFechaEnt.setFont(new java.awt.Font("Kannada Sangam MN", 0, 14)); // NOI18N
        txtFechaEnt.setEnabled(false);
        pnlFondo.add(txtFechaEnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 190, -1));

        lblServicios1.setFont(new java.awt.Font("Kannada MN", 1, 14)); // NOI18N
        lblServicios1.setText("Servicios:");
        pnlFondo.add(lblServicios1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        lblAnticipo.setFont(new java.awt.Font("Kannada MN", 1, 14)); // NOI18N
        lblAnticipo.setText("Anticipo:");
        pnlFondo.add(lblAnticipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, -1, -1));

        lblEntrega1.setFont(new java.awt.Font("Kannada MN", 1, 14)); // NOI18N
        lblEntrega1.setText("Fecha de entrega:");
        pnlFondo.add(lblEntrega1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, -1));

        lblTotal.setFont(new java.awt.Font("Kannada MN", 1, 14)); // NOI18N
        lblTotal.setText("Total:");
        pnlFondo.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, -1, -1));

        txtTelefono.setFont(new java.awt.Font("Kannada Sangam MN", 0, 14)); // NOI18N
        txtTelefono.setEnabled(false);
        pnlFondo.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 190, -1));

        txtTotal.setFont(new java.awt.Font("Kannada Sangam MN", 0, 14)); // NOI18N
        txtTotal.setEnabled(false);
        pnlFondo.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 100, -1));

        txtCliente.setFont(new java.awt.Font("Kannada Sangam MN", 0, 14)); // NOI18N
        txtCliente.setEnabled(false);
        pnlFondo.add(txtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 190, -1));

        txtDireccion.setFont(new java.awt.Font("Kannada Sangam MN", 0, 14)); // NOI18N
        txtDireccion.setEnabled(false);
        pnlFondo.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 190, -1));

        lblRecep.setFont(new java.awt.Font("Kannada MN", 1, 14)); // NOI18N
        lblRecep.setText("Fecha de recepción:");
        pnlFondo.add(lblRecep, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));

        txtFechaRecep.setFont(new java.awt.Font("Kannada Sangam MN", 0, 14)); // NOI18N
        txtFechaRecep.setEnabled(false);
        pnlFondo.add(txtFechaRecep, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 190, -1));

        scrlServicios.setEnabled(false);
        scrlServicios.setFont(new java.awt.Font("Kannada Sangam MN", 0, 13)); // NOI18N

        tblServicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Descripción", "Cantidad", "Precio unitario", "Total", "Detalles", "Perdidas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrlServicios.setViewportView(tblServicios);

        pnlFondo.add(scrlServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 360, 210));

        btnCancelarNota.setBackground(new java.awt.Color(255, 0, 0));
        btnCancelarNota.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelarNota.setText("Cancelar Nota");
        btnCancelarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarNotaActionPerformed(evt);
            }
        });
        pnlFondo.add(btnCancelarNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 510, -1, -1));

        btnEntregar.setBackground(new java.awt.Color(153, 255, 153));
        btnEntregar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEntregar.setText("Realizar Entrega");
        btnEntregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntregarActionPerformed(evt);
            }
        });
        pnlFondo.add(btnEntregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, -1, -1));

        getContentPane().add(pnlFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        dispose();
        FrmConsulNotas frm = new FrmConsulNotas(user);
        frm.setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnCancelarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarNotaActionPerformed
        // TODO add your handling code here:
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Está seguro de cancelar la nota?",
                "Confirmación", JOptionPane.YES_NO_OPTION);

        if (respuesta == JOptionPane.YES_OPTION) {
            // Si el usuario selecciona "Sí"
            System.out.println("El usuario ha seleccionado Sí.");
            if (logica.cancelarNotaRemision(nota.getFolio())) {
                JOptionPane.showMessageDialog(this, "La nota con folio: " + nota.getFolio() + " ha sido cancelada");
                this.setVisible(false);
                FrmNotasRemision notas = new FrmNotasRemision(user);
                notas.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Ocurrio un error al cancelar la nota");
            }
        } else {
            // Si el usuario selecciona "No" o cierra el cuadro de diálogo
            System.out.println("El usuario ha seleccionado No o ha cerrado el cuadro de diálogo.");
        }

    }//GEN-LAST:event_btnCancelarNotaActionPerformed

    private void btnEntregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntregarActionPerformed
        // TODO add your handling code here:
         int respuesta = JOptionPane.showConfirmDialog(null, "¿Está seguro de realizar la entrega de la nota?",
                "Confirmación", JOptionPane.YES_NO_OPTION);

        if (respuesta == JOptionPane.YES_OPTION) {
            // Si el usuario selecciona "Sí"
            System.out.println("El usuario ha seleccionado Sí.");
            Calendar calendarioActual = Calendar.getInstance();
        Date fechaActual = calendarioActual.getTime();
            if (logica.realizarEntrega(nota.getFolio(), fechaActual)) {
                JOptionPane.showMessageDialog(this, "La nota con folio: " + nota.getFolio() + " ha sido entregada");
                this.setVisible(false);
                FrmNotasRemision notas = new FrmNotasRemision(user);
                notas.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Ocurrio un error al entregar la nota");
            }
        } else {
            // Si el usuario selecciona "No" o cierra el cuadro de diálogo
            System.out.println("El usuario ha seleccionado No o ha cerrado el cuadro de diálogo.");
        }
    }//GEN-LAST:event_btnEntregarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarNota;
    private javax.swing.JButton btnEntregar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel lblAnticipo;
    private javax.swing.JLabel lblCliente1;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblEntrega1;
    private javax.swing.JLabel lblNota;
    private javax.swing.JLabel lblRecep;
    private javax.swing.JLabel lblServicios1;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JScrollPane scrlServicios;
    private javax.swing.JTable tblServicios;
    private javax.swing.JTextField txtAnticipo;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtFechaEnt;
    private javax.swing.JTextField txtFechaRecep;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
