/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.itson.presentacion;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import negocio.ILogica;
import negocio.LogicaNegocio;

/**
 *
 * @author alexasoto
 */
public class FrmPrincipal extends javax.swing.JFrame {

    private ILogica logica = new LogicaNegocio();
    private Long user;

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        setResizable(false);
        ImageIcon iconoLogo = new ImageIcon(getClass().getResource("/img/logo.jpg"));
        lblLogo.setIcon(iconoLogo);
        ImageIcon iconoUsuarios = new ImageIcon(getClass().getResource("/img/usuarios.png"));
        btnUsuarios.setIcon(iconoUsuarios);
        ImageIcon iconoClientes = new ImageIcon(getClass().getResource("/img/clientes.png"));
        btnClientes.setIcon(iconoClientes);
        ImageIcon iconoServicios = new ImageIcon(getClass().getResource("/img/servicios.png"));
        btnServicios.setIcon(iconoServicios);
        ImageIcon iconoNotas = new ImageIcon(getClass().getResource("/img/notas.png"));
        btnNotas.setIcon(iconoNotas);
        ImageIcon iconoReportes = new ImageIcon(getClass().getResource("/img/reportes.png"));
        btnReportes.setIcon(iconoReportes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnUsuarios = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnServicios = new javax.swing.JButton();
        btnNotas = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Principal");
        setResizable(false);
        setSize(new java.awt.Dimension(500, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlFondo.setBackground(new java.awt.Color(255, 255, 255));
        pnlFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setBackground(new java.awt.Color(153, 204, 255));
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);

        btnUsuarios.setFont(new java.awt.Font("Kannada MN", 1, 18)); // NOI18N
        btnUsuarios.setText("Usuarios");
        btnUsuarios.setFocusable(false);
        btnUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUsuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        jToolBar1.add(btnUsuarios);

        btnClientes.setFont(new java.awt.Font("Kannada MN", 1, 18)); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.setFocusable(false);
        btnClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        jToolBar1.add(btnClientes);

        btnServicios.setFont(new java.awt.Font("Kannada MN", 1, 18)); // NOI18N
        btnServicios.setText("Servicios");
        btnServicios.setFocusable(false);
        btnServicios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnServicios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServiciosActionPerformed(evt);
            }
        });
        jToolBar1.add(btnServicios);

        btnNotas.setFont(new java.awt.Font("Kannada MN", 1, 18)); // NOI18N
        btnNotas.setText("Notas");
        btnNotas.setFocusable(false);
        btnNotas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNotas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotasActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNotas);

        btnReportes.setFont(new java.awt.Font("Kannada MN", 1, 18)); // NOI18N
        btnReportes.setText("Reportes");
        btnReportes.setFocusable(false);
        btnReportes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReportes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        jToolBar1.add(btnReportes);

        pnlFondo.add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 450));
        pnlFondo.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, -1, -1));

        getContentPane().add(pnlFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private boolean ingresarUsuario() {
        String usuario = JOptionPane.showInputDialog(this, "Ingrese el nombre de usuario");
        if (usuario != null && !usuario.equals("")) {
            String pass;
            JPasswordField passwordField = new JPasswordField();
            int option = JOptionPane.showConfirmDialog(
                    null, passwordField, "Ingrese su contraseña", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
            if (option == JOptionPane.OK_OPTION) {
                char[] password = passwordField.getPassword();
                pass = new String(password);
                this.user = this.logica.autenticarUsuario(usuario, pass);
                if (user != -1) {
                    return true;
                } else {
                    JOptionPane.showMessageDialog(this, "Usuario no encontrado");
                    return false;
                }
            } else {
                JOptionPane.showMessageDialog(this, "Ninguna contraseña ingresada");
                return false;
            }
        } else {
            JOptionPane.showMessageDialog(this, "Ningún usuario ingresado");
            return false;
        }
    }

    private boolean ingresarAdmin() {
        String pass;
        JPasswordField passwordField = new JPasswordField();
        int option = JOptionPane.showConfirmDialog(
                null, passwordField, "Ingrese su contraseña", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        if (option == JOptionPane.OK_OPTION) {
            char[] password = passwordField.getPassword();
            pass = new String(password);
            this.user = this.logica.autenticarUsuario("admin", pass);
            if (user != -1) {
                return true;
            } else {
                JOptionPane.showMessageDialog(this, "Usuario no encontrado");
                return false;
            }
        } else {
            JOptionPane.showMessageDialog(this, "Ninguna contraseña ingresada");
            return false;
        }
    }

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        // TODO add your handling code here:
        if (this.ingresarUsuario()) {
            this.dispose();
            FrmClientes frm = new FrmClientes();
            frm.setVisible(true);
        } else {
            JOptionPane.showConfirmDialog(this, "Error al iniciar sesion");
        }
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        // TODO add your handling code here: 
        if (this.ingresarAdmin()) {
            this.dispose();
            FrmUsuarios frm = new FrmUsuarios();
            frm.setVisible(true);
        }
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServiciosActionPerformed
        // TODO add your handling code here:
        if (this.ingresarUsuario()) {
            this.dispose();
            FrmServicios frm = new FrmServicios();
            frm.setVisible(true);
        } else {
            JOptionPane.showConfirmDialog(this, "Error al iniciar sesion");
        }
    }//GEN-LAST:event_btnServiciosActionPerformed

    private void btnNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotasActionPerformed
        // TODO add your handling code here:
        if (this.ingresarUsuario()) {
            this.dispose();
            FrmNotasRemision frm = new FrmNotasRemision(user);
            frm.setVisible(true);
        } else {
            JOptionPane.showConfirmDialog(this, "Error al iniciar sesion");
        }
    }//GEN-LAST:event_btnNotasActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // TODO add your handling code here:
        if (this.ingresarUsuario()) {
            this.dispose();
            FrmReportes frm = new FrmReportes();
            frm.setVisible(true);
        } else {
            JOptionPane.showConfirmDialog(this, "Error al iniciar sesion");
        }
    }//GEN-LAST:event_btnReportesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnNotas;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnServicios;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JPanel pnlFondo;
    // End of variables declaration//GEN-END:variables
}
